displayName: Block Path
summary: Blocks HTTP requests with a path matching the configured regex.
type: middleware
import: github.com/traefik/plugin-blockpath
compatibility: TODO
testData:
  Regex:
    - "^/foo(.*)"
